-- MySQL Script generated by MySQL Workbench 

-- Sun Oct 23 15:25:01 2022 

-- Model: New Model    Version: 1.0 

-- MySQL Workbench Forward Engineering 

  

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; 

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; 

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; 

  

-- ----------------------------------------------------- 

-- Schema mydb 

-- ----------------------------------------------------- 

  

-- ----------------------------------------------------- 

-- Schema mydb 

-- ----------------------------------------------------- 

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ; 

USE `mydb` ; 

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Plano` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Plano` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `descricao` VARCHAR(55) NOT NULL, 

  `preco` DOUBLE(10,2) NOT NULL, 

  PRIMARY KEY (`id`)) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Contrato` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Contrato` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `inicio_vigencia` DATE NOT NULL, 

  `fim_vigencia` DATE NULL, 

  `plano_id` INT NOT NULL, 

  PRIMARY KEY (`id`), 

  INDEX `fk_Contrato_Plano1_idx` (`plano_id` ASC) VISIBLE, 

  CONSTRAINT `fk_Contrato_Plano1` 

    FOREIGN KEY (`plano_id`) 

    REFERENCES `mydb`.`Plano` (`id`) 

    ON DELETE NO ACTION 

    ON UPDATE NO ACTION) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Cliente` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` ( 

  `id` INT(11) NOT NULL AUTO_INCREMENT, 

  `nome` VARCHAR(255) NOT NULL, 

  `email` VARCHAR(55) NOT NULL, 

  `senha` CHAR(60) NOT NULL, 

  `id_contrato` INT NOT NULL, 

  PRIMARY KEY (`id`), 

  INDEX `fk_Cliente_Contratacao_idx` (`id_contrato` ASC) VISIBLE, 

  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE, 

  CONSTRAINT `fk_Cliente_Contratacao` 

    FOREIGN KEY (`id_contrato`) 

    REFERENCES `mydb`.`Contrato` (`id`) 

    ON DELETE NO ACTION 

    ON UPDATE NO ACTION) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Limite_Gastos` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Limite_Gastos` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `valor` DOUBLE(10,2) NOT NULL, 

  `id_cliente` INT(11) NOT NULL, 

  PRIMARY KEY (`id`), 

  INDEX `fk_Limite_Gastos_Cliente1_idx` (`id_cliente` ASC) VISIBLE, 

  CONSTRAINT `fk_Limite_Gastos_Cliente1` 

    FOREIGN KEY (`id_cliente`) 

    REFERENCES `mydb`.`Cliente` (`id`) 

    ON DELETE CASCADE 

    ON UPDATE NO ACTION) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Conta` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Conta` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `nome` VARCHAR(45) NOT NULL, 

  `banco` VARCHAR(45) NOT NULL, 

  `cliente_id` INT(11) NOT NULL, 

  `id_limite_gastos` INT NULL, 

  PRIMARY KEY (`id`), 

  INDEX `fk_Conta_Cliente1_idx` (`cliente_id` ASC) VISIBLE, 

  INDEX `fk_Conta_Limite_Gastos1_idx` (`id_limite_gastos` ASC) VISIBLE, 

  CONSTRAINT `fk_Conta_Cliente1` 

    FOREIGN KEY (`cliente_id`) 

    REFERENCES `mydb`.`Cliente` (`id`) 

    ON DELETE CASCADE 

    ON UPDATE NO ACTION, 

  CONSTRAINT `fk_Conta_Limite_Gastos1` 

    FOREIGN KEY (`id_limite_gastos`) 

    REFERENCES `mydb`.`Limite_Gastos` (`id`) 

    ON DELETE NO ACTION 

    ON UPDATE NO ACTION) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Categoria` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `descricao` VARCHAR(55) NOT NULL, 

  `limite_gastos_id` INT NULL, 

  PRIMARY KEY (`id`), 

  INDEX `fk_Categoria_Limite_Gastos1_idx` (`limite_gastos_id` ASC) VISIBLE, 

  CONSTRAINT `fk_Categoria_Limite_Gastos1` 

    FOREIGN KEY (`limite_gastos_id`) 

    REFERENCES `mydb`.`Limite_Gastos` (`id`) 

    ON DELETE CASCADE 

    ON UPDATE NO ACTION) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Via_Pagamento` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Via_Pagamento` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `descricao` VARCHAR(45) NOT NULL, 

  PRIMARY KEY (`id`)) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Lancamento` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Lancamento` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `descricao` VARCHAR(255) NOT NULL, 

  `valor` DOUBLE(10,2) NOT NULL, 

  `data_lancamento` DATETIME NOT NULL, 

  `tipo_lancamento` VARCHAR(45) NOT NULL, 

  `conta_id` INT NOT NULL, 

  `categoria_id` INT NULL, 

  `id_cliente` INT(11) NOT NULL, 

  `id_via_pagamento` INT NOT NULL, 

  PRIMARY KEY (`id`), 

  INDEX `fk_Lancamento_Conta1_idx` (`conta_id` ASC) VISIBLE, 

  INDEX `fk_Lancamento_Categoria1_idx` (`categoria_id` ASC) VISIBLE, 

  INDEX `fk_Lancamento_Cliente1_idx` (`id_cliente` ASC) VISIBLE, 

  INDEX `fk_Lancamento_Via_Pagamento1_idx` (`id_via_pagamento` ASC) VISIBLE, 

  CONSTRAINT `fk_Lancamento_Conta1` 

    FOREIGN KEY (`conta_id`) 

    REFERENCES `mydb`.`Conta` (`id`) 

    ON DELETE CASCADE 

    ON UPDATE NO ACTION, 

  CONSTRAINT `fk_Lancamento_Categoria1` 

    FOREIGN KEY (`categoria_id`) 

    REFERENCES `mydb`.`Categoria` (`id`) 

    ON DELETE NO ACTION 

    ON UPDATE NO ACTION, 

  CONSTRAINT `fk_Lancamento_Cliente1` 

    FOREIGN KEY (`id_cliente`) 

    REFERENCES `mydb`.`Cliente` (`id`) 

    ON DELETE NO ACTION 

    ON UPDATE NO ACTION, 

  CONSTRAINT `fk_Lancamento_Via_Pagamento1` 

    FOREIGN KEY (`id_via_pagamento`) 

    REFERENCES `mydb`.`Via_Pagamento` (`id`) 

    ON DELETE NO ACTION 

    ON UPDATE NO ACTION) 

ENGINE = InnoDB; 

  

  

-- ----------------------------------------------------- 

-- Table `mydb`.`Cartao` 

-- ----------------------------------------------------- 

CREATE TABLE IF NOT EXISTS `mydb`.`Cartao` ( 

  `id` INT NOT NULL AUTO_INCREMENT, 

  `descricao` VARCHAR(45) NOT NULL, 

  `limite` DOUBLE(10,2) NOT NULL, 

  `data_vencimento` DATE NOT NULL, 

  `data_fechamento` DATE NOT NULL, 

  `conta_pagamento_id` INT NOT NULL, 

  `via_pagamento_id` INT NOT NULL, 

  PRIMARY KEY (`id`), 

  INDEX `fk_Cartao_Conta1_idx` (`conta_pagamento_id` ASC) VISIBLE, 

  INDEX `fk_Cartao_Via_Pagamento1_idx` (`via_pagamento_id` ASC) VISIBLE, 

  CONSTRAINT `fk_Cartao_Conta1` 

    FOREIGN KEY (`conta_pagamento_id`) 

    REFERENCES `mydb`.`Conta` (`id`) 

    ON DELETE CASCADE 

    ON UPDATE NO ACTION, 

  CONSTRAINT `fk_Cartao_Via_Pagamento1` 

    FOREIGN KEY (`via_pagamento_id`) 

    REFERENCES `mydb`.`Via_Pagamento` (`id`) 

    ON DELETE NO ACTION 

    ON UPDATE NO ACTION) 

ENGINE = InnoDB; 

  

  

SET SQL_MODE=@OLD_SQL_MODE; 

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; 

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; 